# Dependencies
markdown: kramdown
highlighter: rouge

# Gems
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-redirect-from
  - jekyll-seo-tag

# Settings
exclude:
  [
    CNAME,
    README.md,
    LICENSE.md,
    .gitignore,
    package.json,
    package-lock.json,
    yarn.lock,
    _js,
    _scss,
    _images,
    build.mjs,
    node_modules,
    Gemfile,
    Gemfile.lock,
    prettier.config.js,
  ]
permalink: /:title/
compress_html:
  clippings: all
  comments: all
dark_theme: false

# Site meta
title: borterion
tagline: physicist | artist
keywords: 'physics, art, music, archeology'
description: 'A phyisicist making art with the universe'
url: https://borterion.art
baseurl: '/'
assets: '/assets'
images: '/images'
logo: /ass/ets/apple-icon-144x144.png # Cambiar

author:
  name: Carlos Darío Badilla Cerdas
  url: http://borterion.art
  email: bor@borterion.art
  twitter: borterion

social:
  twitter: https://twitter.com/Borterion
  #instagram: https://instagram.com/borterion
  #github: https://github.com/borterion/spring
  #medium: https://medium.com/@borterion

version: 4.0.0

github:
  repo: https://github.com/connor-baer/springindex

# Integrations
# typekit:              fcv7rfe

google_fonts:
  PT Sans: 400, 700
  PT Serif: 400, 700
  Playfair Display: 400

google_analytics_key: UA-94021817-2
# google_site_verification: Z-pc_HPc4XNBz8xg1fgtxO2MSIYLirZc2jWTNq0bJyM

# Content
excerpt_separator: <!-- Read more -->

navigation:
  Medium: https://medium.com/@borterion
  Twitter: https://twitter.com/Borterion
  Github: https://github.com/borterion
